"""Added penalizations

Revision ID: 027dcc5db289
Revises: 2fc028dbc8da
Create Date: 2024-03-03 16:22:19.555713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027dcc5db289'
down_revision = '2fc028dbc8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penalizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('competition_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penalizations_id'), 'penalizations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_penalizations_id'), table_name='penalizations')
    op.drop_table('penalizations')
    # ### end Alembic commands ###
