"""Added payment comprovative to inscriptions

Revision ID: 2fc028dbc8da
Revises: 5eb00eae17b9
Create Date: 2024-02-16 14:28:03.052334

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2fc028dbc8da"
down_revision = "5eb00eae17b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inscriptions",
        sa.Column("payment_comprovative_url", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inscriptions", "payment_comprovative_url")
    # ### end Alembic commands ###
