"""Added coach certificates

Revision ID: 52e4f79a5241
Revises: 11b2f8b0658e
Create Date: 2024-01-29 22:21:34.629248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e4f79a5241'
down_revision = '11b2f8b0658e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurances', sa.Column('coach_certificate_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurances', 'coach_certificate_url')
    # ### end Alembic commands ###
