"""Save files medical exam and payment

Revision ID: 5801661f6b47
Revises: dcd91a545eba
Create Date: 2023-12-05 20:58:53.677001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5801661f6b47'
down_revision = 'dcd91a545eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurances', sa.Column('medical_exam_url', sa.String(length=255), nullable=True))
    op.add_column('insurances', sa.Column('payment_comprovative_url', sa.String(length=255), nullable=True))
    op.alter_column('insurances', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('insurances', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insurances', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('insurances', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('insurances', 'payment_comprovative_url')
    op.drop_column('insurances', 'medical_exam_url')
    # ### end Alembic commands ###
