"""Added price to tournaments

Revision ID: 5eb00eae17b9
Revises: e919b6e0ad76
Create Date: 2024-02-13 12:55:36.454723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb00eae17b9'
down_revision = 'e919b6e0ad76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'price')
    # ### end Alembic commands ###
