"""Add notes to insurances

Revision ID: 899403b1c419
Revises: b5f1016be25a
Create Date: 2023-12-16 13:10:39.470279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899403b1c419'
down_revision = 'b5f1016be25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurances', sa.Column('notes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurances', 'notes')
    # ### end Alembic commands ###
