"""Sub team groups for insurances

Revision ID: 89d72ad067cc
Revises: f5c2e78b75f1
Create Date: 2023-12-05 16:07:05.931932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d72ad067cc'
down_revision = 'f5c2e78b75f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurances', sa.Column('sub_team_group', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_insurances_sub_team_group'), 'insurances', ['sub_team_group'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insurances_sub_team_group'), table_name='insurances')
    op.drop_column('insurances', 'sub_team_group')
    # ### end Alembic commands ###
