"""Add profile_picture_url for athletes

Revision ID: b5f1016be25a
Revises: 5801661f6b47
Create Date: 2023-12-16 10:12:15.179548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b5f1016be25a"
down_revision = "5801661f6b47"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "athletes", sa.Column("profile_picture_url", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("athletes", "profile_picture_url")
    # ### end Alembic commands ###
