"""Update insurances

Revision ID: dcd91a545eba
Revises: 89d72ad067cc
Create Date: 2023-12-05 17:32:00.112274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "dcd91a545eba"
down_revision = "89d72ad067cc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_insured_types_id", table_name="insured_types")
    op.drop_index("ix_insured_types_name", table_name="insured_types")
    op.drop_constraint(
        "insured_entities_insured_type_id_fkey", "insured_entities", type_="foreignkey"
    )
    op.drop_table("insured_types")
    op.add_column("insurances", sa.Column("start_date", sa.DateTime(), nullable=True))
    op.add_column("insurances", sa.Column("end_date", sa.DateTime(), nullable=True))
    op.drop_column("insurances", "insurance_end_date")
    op.drop_column("insurances", "insurance_start_date")
    op.drop_column("insured_entities", "updated_at")
    op.drop_column("insured_entities", "created_at")
    op.drop_column("insured_entities", "insured_type_id")
    op.drop_column("insured_entities", "deleted_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "insured_entities",
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "insured_entities",
        sa.Column("insured_type_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "insured_entities",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "insured_entities",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "insured_entities_insured_type_id_fkey",
        "insured_entities",
        "insured_types",
        ["insured_type_id"],
        ["id"],
    )
    op.add_column(
        "insurances",
        sa.Column(
            "insurance_start_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "insurances",
        sa.Column(
            "insurance_end_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("insurances", "end_date")
    op.drop_column("insurances", "start_date")
    op.create_table(
        "insured_types",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="insured_types_pkey"),
    )
    op.create_index("ix_insured_types_name", "insured_types", ["name"], unique=False)
    op.create_index("ix_insured_types_id", "insured_types", ["id"], unique=False)
    # ### end Alembic commands ###
