"""Update Insurances

Revision ID: f5c2e78b75f1
Revises: d74999d0ff55
Create Date: 2023-12-04 13:51:27.699788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5c2e78b75f1'
down_revision = 'd74999d0ff55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_federation_request_id', table_name='federation_request')
    op.drop_table('federation_request')
    op.add_column('insurances', sa.Column('status', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurances', 'status')
    op.create_table('federation_request',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('athlete_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', 'denied', 'requested', 'other', name='federationrequestsenum'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], name='federation_request_athlete_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='federation_request_pkey'),
    sa.UniqueConstraint('athlete_id', 'year', name='federation_request_athlete_id_year_key')
    )
    op.create_index('ix_federation_request_id', 'federation_request', ['id'], unique=False)
    # ### end Alembic commands ###
