from .crud_user import user
from .crud_role import role
from .crud_user_role import user_role
from .crud_athlete import athlete
from .crud_team import team
from .crud_competition import competition
from .crud_tournament import tournament
from .crud_athlete_competition import athlete_competition
from .crud_match import match
from .crud_category import category
from .crud_category_type import category_type
from .crud_belt import belt
from .crud_athlete_group import athlete_group
from .crud_inscription import inscription
from .crud_insurance_type import insurance_type
from .crud_insurance_group import insurance_group
from .crud_insurance import insurance
from .crud_insured_entity import insured_entity
from .crud_responsible import responsible
from .crud_identification_document import identification_document
from .crud_address import address
from .crud_private_info import private_info
from .crud_penalization import penalization
